name: 'Build and Test'
on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  build_dotnet_project:
    runs-on: ubuntu-latest
    name: Build, test and upload dotnet artifact
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x

      - name: Build
        run: |
          dotnet build -c Release ./Source/Settings.Extensions.Configuration/Settings.Extensions.Configuration.csproj -p:RepositoryCommit=${{ github.sha }} -p:RevisionNumber=$(git rev-list --count HEAD) -p:BuildNumber=${{ github.run_number }}

      - name: Test
        run: |
          dotnet test ./Test/Settings.Extensions.Configuration.Tests/Settings.Extensions.Configuration.Tests.csproj

      - name: Upload nupkg
        uses: actions/upload-artifact@v3
        with:
          name: main-package
          path: | 
            Source/Settings.Extensions.Configuration/bin/Release/*.nupkg
            mainversion
